name: RootsCounter
description: A sample command-line application.
version: 0.0.1
author: vpotseluyko <vyacheslav.potseluyko@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  console: "^2.2.4"


dev_dependencies:
  test: ^0.12.0
